name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'renovate'
change-template: '- $TITLE (#$NUMBER)'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: $CHANGES
