name: Documentation
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew dokkaHtmlMultiModule
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/gh-pages
