name: Publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew check
      - run: >-
          ./gradlew
          -PVERSION_NAME='${{ github.ref_name }}'
          -PsigningInMemoryKey='${{ secrets.SIGNING_KEY }}'
          -PsigningInMemoryKeyPassword='${{ secrets.SIGNING_PASSWORD }}'
          -PmavenCentralUsername='${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}'
          -PmavenCentralPassword='${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}'
          publish
